spring:
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:~/subway
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data-initial.sql
